"""protocols v2 — types, completions, documents

Revision ID: 61c43df49a56
Revises: 36935aa0bf3b
Create Date: 2026-04-11 09:42:13.373363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c43df49a56'
down_revision = '36935aa0bf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'user_id', 'date', name='uq_protocol_completion_per_day')
    )
    op.create_table('protocol_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'document_id', name='uq_protocol_document')
    )
    op.create_index("idx_protocol_completions_user_date", "protocol_completions", ["user_id", "date"])
    op.create_index("idx_protocol_completions_protocol", "protocol_completions", ["protocol_id"])

    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), server_default='task', nullable=False))
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), server_default='task', nullable=False))
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekly_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('icon')
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('weekly_target')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('activity_type')
        batch_op.drop_column('type')

    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('activity_type')
        batch_op.drop_column('type')

    op.drop_table('protocol_documents')
    op.drop_index("idx_protocol_completions_protocol", table_name="protocol_completions")
    op.drop_index("idx_protocol_completions_user_date", table_name="protocol_completions")
    op.drop_table('protocol_completions')
    # ### end Alembic commands ###
